#!/bin/sh

# t2e: Send text to the Emacs kill ring.
#
# With no arguments, send the contents of the X clipboard to the Emacs kill ring.
# With -r, first set the clipboard to the contents read from standard input.
# With -s, instead send X primary selection to the Emacs kill ring.

if [ "${1}" = '-r' ]; then
    exec xclip -sel clip -i -f | \
        emacsclient -e "(kill-new \"$(sed 's/[\"]/\\&/g')\")"
elif [ "${1}" = '-s' ]; then
    exec xclip -o | \
        emacsclient -e "(kill-new \"$(sed 's/[\"]/\\&/g')\")"
else
    exec xclip -sel clip -o | \
        emacsclient -e "(kill-new \"$(sed 's/[\"]/\\&/g')\")"
fi
