#!/bin/sh

# With -r, send the contents read from standard input first to the X clipboard,
# then to the Emacs kill ring if an Emacs daemon is running as the current user.

# With -s, send the X primary selection contents to the X clipboard and the
# Emacs kill ring if an Emacs daemon is running as the current user.

# With no arguments, send the contents of the X clipboard to the Emacs kill ring
# if an Emacs daemon is running as the current user.

id=$(id -u)

if pgrep -q -u "$id" -f 'emacs --daemon'; then
    if [ "${1}" = '-r' ]; then
        exec xclip -sel clip -i -f | \
            emacsclient -e "(kill-new \"$(sed 's/[\"]/\\&/g')\")"
    elif [ "${1}" = '-s' ]; then
        exec xclip -o | \
            xclip -sel clip -i -f | \
            emacsclient -e "(kill-new \"$(sed 's/[\"]/\\&/g')\")"
    else
        exec xclip -sel clip -o | \
                        emacsclient -e "(let ((interprogram-cut-function nil))
(kill-new \"$(sed 's/[\"]/\\&/g')\"))"
    fi
else
    if [ "${1}" = '-r' ]; then
        exec xclip -sel clip -i -f
    fi
fi
