#!/bin/sh
#
# pdfsplit [input.pdf] [first_page] [last_page] [output.pdf]
#

if [ $# -ne 4 ]
then
        echo "Usage: pdfsplit input.pdf first_page last_page output.pdf"
        exit 1
fi
gs -dBATCH -dNOPAUSE -dQUIET -sDEVICE=pdfwrite -sOutputFile="$4" \
   -dFirstPage="$2" -dLastPage="$3" "$1"
