#!/bin/sh

# Load my usual tmux session

hosts="ala ser met freefall"

if ! ssh-add -l | grep -q 'yoEOEisOxm1pe4bZgLSDsGUJyzEnt9/L8qTwlK3PrQ0'; then
  ssh-add ~/.ssh/freebsd_rsa
fi

i=2
for h in $hosts; do
  tmux neww\; send -t :$i "ssh $h" KPEnter "ta" KPEnter
  i=$((i+1))
done

#tmux neww\; send "scli" KPEnter
#sleep 1
#tmux renamew -t :$i "scli"
#tmux set-option -t :$i allow-rename off
