#!/bin/sh

# Unload my usual tmux session

for i in $(seq 2 7)
do
  tmux send -t ":$i" -l "tmux detach"
  tmux send -t ":$i" KPEnter
done
tmux send -t :8 -l ":q"
tmux send -t :8 KPEnter

sleep 1

for i in $(seq 2 7)
do
  tmux send -t ":$i" -l "exit"
  tmux send -t ":$i" KPEnter
done

sleep 1

for i in $(seq 2 8)
do
  tmux send -t ":$i" -l "exit"
  tmux send -t ":$i" KPEnter
done
