#!/bin/sh

# Unload my usual tmux session

hosts="ala ser met freefall.freebsd.org"
#scli_num=5

i=2
for h in $hosts; do
  echo $h
  if ping -c1 -W100 "$h" >/dev/null; then
    ssh "$h" 'tmux detach'
  fi
  i=$((i+1))
done

# close scli
#tmux send -t ":$i" -l ":q"
#tmux send -t ":$i"  KPEnter


for j in $(seq 2 $((i-1))); do
  tmux send -t ":$j" -l "exit"
  tmux send -t ":$j" KPEnter
done

sleep 1

for j in $(seq 2 $((i-1))); do
  tmux kill-window -t ":$j"
done
