#!/bin/sh

# Unload my usual tmux session

hosts="ala awarnach bravo freefall gly storage2"

for h in $hosts; do
  ssh "$h" 'tmux detach'
done

tmux send -t :8 -l ":q"
tmux send -t :8 KPEnter

sleep 1

for i in $(seq 2 7)
do
  tmux send -t ":$i" -l "exit"
  tmux send -t ":$i" KPEnter
done

sleep 1

for i in $(seq 2 8)
do
  tmux send -t ":$i" -l "exit"
  tmux send -t ":$i" KPEnter
done
